export const BUTTON_SIZE = 56;
export const ITEM_SIZE = 36;
export const CONTAINER_SIZE = ITEM_SIZE * 3.5;
export const RADIUS = CONTAINER_SIZE / 2;
export const MARGIN_RIGHT = 8;
export const PRIMARY = "#2ea09b";
export const PRIMARY_2 = "#268e89";
export const BORDER = "#dadada";
export const TEXT = "#656565";
